<?php
/**
 * @var OneTap $block
 * @var Escaper $escaper
 */

use PeachCode\GoogleOneTap\Block\OneTap;
use Magento\Framework\Escaper;

if (!$block->isCustomerLoggedIn() && $block->isEnable()) :
    $clientId = $escaper->escapeHtml($block->getClientId());
    $loginUri = $escaper->escapeUrl($block->getUrl('customer/account'));
    $positionClass = $escaper->escapeHtml($block->getPosition());

    $autoSign = $block->getAutoSign() ? 'data-auto_select="true"' : '';
    $cancelOnTapOutside = (!$block->getClickDisable() && !$block->getAutoSign())
        ? 'data-cancel_on_tap_outside="false"'
        : '';
    ?>
    <!-- Google One Tap Container -->
    <div id="g_id_onload"
         data-client_id="<?= $clientId ?>"
         data-context="signin"
         data-callback="googleLoginEndpoint"
         data-login_uri="<?= $loginUri ?>"
         data-itp_support="true"
        <?= $autoSign ?>
        <?= $cancelOnTapOutside ?>>
    </div>

    <!-- Google One Tap Callback Script -->
    <script>
        function googleLoginEndpoint(googleUser) {
            const xhr = new XMLHttpRequest();
            xhr.open("POST", window.BASE_URL + "onetaplogin/checkout/response", true);
            xhr.onreadystatechange = function () {
                if (xhr.readyState === 4 && xhr.status === 200) {
                    require(['Magento_Customer/js/customer-data'], function(customerData) {
                        customerData.reload(['customer', 'cart'], true);
                    });
                    window.location.reload();
                }
            };

            const formData = new FormData();
            formData.append("id_token", googleUser.credential);
            xhr.send(formData);
        }
    </script>

    <!-- Add Position Class to Google Picker Container -->
    <script>
        require(['jquery'], function ($) {
            $(function () {
                const interval = setInterval(function () {
                    const container = $('#credential_picker_container');
                    if (container.length) {
                        container.addClass("<?= $positionClass ?>");
                        clearInterval(interval);
                    }
                }, 100);
            });
        });
    </script>
<?php endif; ?>
