<?php
/**
 * @var OneTap $block
 * @var Escaper $escaper
 */

use PeachCode\GoogleOneTap\Block\OneTap;
use Magento\Framework\Escaper;

if (!$block->isCustomerLoggedIn() && $block->isEnable()) :
    $clientId = $escaper->escapeHtml($block->getClientId());
    $loginUri = $escaper->escapeUrl($block->getUrl('customer/account'));
    $positionClass = $escaper->escapeHtml($block->getPosition());

    $autoSign = $block->getAutoSign() ? 'data-auto_select="true"' : '';
    $cancelOnTapOutside = (!$block->getClickDisable() && !$block->getAutoSign())
        ? 'data-cancel_on_tap_outside="false"'
        : '';
    ?>
    <!-- Google One Tap Container -->
    <div id="g_id_onload"
         data-client_id="<?= $clientId ?>"
         data-context="signin"
         data-callback="googleLoginEndpoint"
         data-login_uri="<?= $loginUri ?>"
         data-itp_support="true"
        <?= $autoSign ?>
        <?= $cancelOnTapOutside ?>>
    </div>

    <!-- Google One Tap Callback Script -->
    <script type="text/x-magento-init">
        {
            "*": {
                "PeachCode_GoogleOneTap/js/onetap-callback": {
                    "positionClass": "<?= $positionClass ?>"
                    }
                }
        }
    </script>
<?php endif; ?>
